CREATE TABLE IF NOT EXISTS borrower (
    borrower_key INTEGER PRIMARY KEY,
    emp_length TEXT,
    emp_title TEXT,
    home_ownership TEXT,
    addr_state TEXT,
    zip_code TEXT,
    annual_inc DECIMAL
);
CREATE TABLE IF NOT EXISTS credit_history (
    credit_history_key INTEGER PRIMARY KEY,
    fico_range_high DECIMAL,
    fico_range_low DECIMAL,
    acc_now_delinq DECIMAL,
    acc_open_past_24mths DECIMAL,
    all_util DECIMAL,
    avg_cur_bal DECIMAL,
    bc_open_to_buy DECIMAL,
    bc_util DECIMAL,
    chargeoff_within_12_mths DECIMAL,
    collections_12_mths_ex_med DECIMAL,
    delinq_2yrs DECIMAL,
    delinq_amnt DECIMAL,
    earliest_cr_line TEXT,
    il_util DECIMAL,
    inq_fi DECIMAL,
    inq_last_12m DECIMAL,
    inq_last_6mths DECIMAL,
    max_bal_bc DECIMAL,
    mo_sin_old_il_acct DECIMAL,
    mths_since_rcnt_il DECIMAL,
    mo_sin_old_rev_tl_op DECIMAL,
    mo_sin_rcnt_rev_tl_op DECIMAL,
    mo_sin_rcnt_tl DECIMAL,
    mort_acc DECIMAL,
    mths_since_last_delinq DECIMAL,
    mths_since_last_major_derog DECIMAL,
    mths_since_last_record DECIMAL,
    mths_since_recent_bc DECIMAL,
    mths_since_recent_bc_dlq DECIMAL,
    mths_since_recent_inq DECIMAL,
    mths_since_recent_revol_delinq DECIMAL,
    num_accts_ever_120_pd DECIMAL,
    num_actv_bc_tl DECIMAL,
    num_actv_rev_tl DECIMAL,
    num_bc_sats DECIMAL,
    num_bc_tl DECIMAL,
    num_il_tl DECIMAL,
    num_op_rev_tl DECIMAL,
    num_rev_accts DECIMAL,
    num_rev_tl_bal_gt_0 DECIMAL,
    num_sats DECIMAL,
    num_tl_120dpd_2m DECIMAL,
    num_tl_30dpd DECIMAL,
    num_tl_90g_dpd_24m DECIMAL,
    num_tl_op_past_12m DECIMAL,
    open_acc DECIMAL,
    open_acc_6m DECIMAL,
    open_il_12m DECIMAL,
    open_il_24m DECIMAL,
    open_act_il DECIMAL,
    open_rv_12m DECIMAL,
    open_rv_24m DECIMAL,
    pct_tl_nvr_dlq DECIMAL,
    percent_bc_gt_75 DECIMAL,
    pub_rec DECIMAL,
    pub_rec_bankruptcies DECIMAL,
    revol_bal DECIMAL,
    revol_util  TEXT,
    tax_liens DECIMAL,
    total_acc TEXT,
    total_cu_tl DECIMAL,
    sec_app_fico_range_low DECIMAL,
    sec_app_fico_range_high DECIMAL,
    sec_app_earliest_cr_line TEXT,
    sec_app_inq_last_6mths DECIMAL,
    sec_app_mort_acc DECIMAL,
    sec_app_open_acc DECIMAL,
    sec_app_revol_util DECIMAL,
    sec_app_open_act_il DECIMAL,
    sec_app_num_rev_accts DECIMAL,
    sec_app_chargeoff_within_12_mths DECIMAL,
    sec_app_collections_12_mths_ex_med DECIMAL
);


